let songs = [
  { title: "295", file: "https://oyepriyansh.pages.dev/i/modi-ers65d4/295.mp3" },
  { title: "Bedardeya", file: "https://oyepriyansh.pages.dev/i/modi-ers65d4/bedardeya.mp3" },
  { title: "Bewafa", file: "https://oyepriyansh.pages.dev/i/modi-ers65d4/bewafa.mp3" },
  { title: "Brown Rang", file: "https://oyepriyansh.pages.dev/i/modi-ers65d4/brown-rang.mp3" },
  { title: "Cheques", file: "https://oyepriyansh.pages.dev/i/modi-ers65d4/cheques.mp3" },
  { title: "Desi Kalakaar", file: "https://oyepriyansh.pages.dev/i/modi-ers65d4/desi-kalakaar.mp3" },
  { title: "Dope Shope", file: "https://oyepriyansh.pages.dev/i/modi-ers65d4/dope-shope.mp3" },
  { title: "Haryana", file: "https://oyepriyansh.pages.dev/i/modi-ers65d4/haryana.mp3" },
  { title: "Heeriye", file: "https://oyepriyansh.pages.dev/i/modi-ers65d4/heeriye.mp3" },
  { title: "Kalastaar", file: "https://oyepriyansh.pages.dev/i/modi-ers65d4/kalastaar.mp3" },
  { title: "Kolaveri", file: "https://oyepriyansh.pages.dev/i/modi-ers65d4/kolaveri.mp3" },
  { title: "Kuley Kuley", file: "https://oyepriyansh.pages.dev/i/modi-ers65d4/kuley.mp3" },
  { title: "Levels", file: "https://oyepriyansh.pages.dev/i/modi-ers65d4/levels.mp3" },
  { title: "Libaas", file: "https://oyepriyansh.pages.dev/i/modi-ers65d4/libaas.mp3" },
  { title: "Obsessed", file: "https://oyepriyansh.pages.dev/i/modi-ers65d4/obsessed.mp3" },
  { title: "One Love", file: "https://oyepriyansh.pages.dev/i/modi-ers65d4/onelove.mp3" },
  { title: "Saadi Gali Aaja", file: "https://oyepriyansh.pages.dev/i/modi-ers65d4/sadi-gali.mp3" },
  { title: "Systumm", file: "https://oyepriyansh.pages.dev/i/modi-ers65d4/systumm.mp3" },
  { title: "Yadav Brand", file: "https://oyepriyansh.pages.dev/i/modi-ers65d4/yadav.mp3" },
];